title: Housing and Homelessness
description: An economic seminar focus on issues related to housing for low-income families
theme: just-the-docs

url: https://pharringtonp19.github.io/housing-and-homelessness

#logo: "/assets/images/housing_homelessness_logo.png"

favicon_ico: "/assets/images/hh2.png"

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template


#   title: YOUR TITLE
# description: YOUR DESCRIPTION
# theme: just-the-docs

# url: https://YOUR-USERNAME.github.io/YOUR-SITE-NAME

# aux_links: # remove if you don't want this link to appear on your pages
#   Template Repository: https://github.com/YOUR-USERNAME/YOUR-SITE-NAME
